### ISSUE TITLE
could we increase the width of the blog post or decrease the font size?

### ISSUE THREAD

**Issue by pmlopes** [vert-x3/vertx-web-site#112]
In the blog there are almost all the times code listings and although we do not write very long lines in general they end up almost all the time wrapped. I think it makes reading the code harder so readers will just skim and go over missing probably important pieces of information.

Currently we only allocate 66.6% of the screen real-estate for the blog area, which means we're wasting 33% of space showing just white :-/

**Comment by pmlopes** [comment]
As a note github blog uses font size 16px and we have 18px

**Comment by michel-kraemer** [comment]
Well 18px is the base font-size of the whole website. We shouldn't change this to keep the overall layout.

If you click on a post title the sidebar (with the recent posts) will disappear and the text becomes wider. This should be wide enough for almost all content. We can probably solve the problem by putting only abstract/excerpts on the front page.

In addition we can set the `overflow-x: scroll` property on the code block so that it doesn't wrap but display a scroll bar. In most cases this makes the code much more readable (although you sometimes have to scroll now, but in my experience it's still a lot better).

**Comment by pmlopes** [comment]
Yes i agree scrolling bars on code are probably better than wrapping

**Comment by pmlopes** [comment]
I think that scrolls for code areas and the suggestion of read-more for content on the front page as @cescoffier suggested in https://github.com/vert-x3/vertx-web-site/issues/111 would be a great improvement

**Comment by michel-kraemer** [comment]
Cool. I can contribute the change when I have time on the weekend.
