### ISSUE TITLE
Who's using Vert.x - new page

### ISSUE THREAD

**Issue by purplefox** [vert-x3/vertx-web-site#27]
So far, I have about 16 companies who have given permission for their logos to appear in the "Who's using Vert.x?" section, and this number is likely to increase over time.

This is quite a lot, so I'm wondering whether we should put them on a different page to the home page - or perhaps we put a few on the home page and click through more.... to another page with the rest.

Thoughts?

**Comment by michel-kraemer** [comment]
I think, we should only put large or well-known companies to the homepage (this section is all about impressing people, isn't? ^^). Then we can add a link to a separate page to see the rest.

However, I guess 16 isn't too much. If you look at the Groovy webpage, for example, they have 36 companies listed and it still looks OK.

We might have to make a cut eventually and decide who's really going there and who we might have to reject. Otherwise we risk that every small one-man company sends us their logo. WDYT?

**Comment by purplefox** [comment]
I agree - only well known companies on the homepage, then we link to another page.

I don't mind too much if the other companies are small or not well known, I'd consider it a perk of being in the Vert.x community (and a thank you from us) that you can get some free advertising for your company :)

**Comment by michel-kraemer** [comment]
See new pull request #56
