### ISSUE TITLE
Add logo to who's using vert.x

### ISSUE THREAD

**Issue by adrianluisgonzalez** [vert-x3/vertx-web-site#86]
Please add our logo to who's using vert.x

I have provided the logos in black or white (you can't see the white on white, but I promise it is attached)

Please link to: http://www.ef.edu
![black_ef_180](https://cloud.githubusercontent.com/assets/1521539/8412439/fc81c8ac-1e57-11e5-9db0-e13e75cb0e74.png)
![white_ef_180](https://cloud.githubusercontent.com/assets/1521539/8412441/fdfa236e-1e57-11e5-8e2e-ab4501151d15.png)

**Comment by purplefox** [comment]
Hi Adrian,

I think we need a transparent border on the left and right hand sides of the image otherwise it dominates the other logos on the page, because it's so relatively tall.

Unfortunately my gimp skills aren't really up to doing that :(

Any chance you could edit it?

BTW, if you want to preview how it looks on the web site, simply clone this repository, then add the logo in the src/assets/user_logos.dir, then edit the file src/main/whos_using/users.js to add entry for education first.

Then build the project:

mvn clean site

Then run it locally:

gulp watch

Then point your browser to localhost:4040

**Comment by cescoffier** [comment]
gulp watch open the HTTP server on the port 4000 (not 4040)

So the sequence is:

```
mvn clean install site
gulp watch
```

**Comment by purplefox** [comment]
+1

**Comment by eriyanto** [comment]
![eprocurement-indonesia-logo](https://cloud.githubusercontent.com/assets/11383742/8647078/0653a1b6-297f-11e5-97ec-78251292c8f7.png)

This is my Product logo that using vert.x Technology, with detail information feature can be shown at http://eprocurement-indonesia.com/

**Comment by adrianluisgonzalez** [comment]
@purplefox my skills aren't up to the task either.  I'll get someone to sort out the borders.  Thanks.

**Comment by adrianluisgonzalez** [comment]
![ef_white_newdimensions](https://cloud.githubusercontent.com/assets/1521539/8703422/05e95532-2aeb-11e5-8138-f74f41b2108d.png)

I have attached an updated logo with transparent left/right boarders.  The logo is white so it is hard to see it on github.
